title: Parents & School Community Address
description: Mx. Chang | Robotics Educator | (808) 555-1234 | pchang6@hawaii.edu
background: /extras/image.png
google_analytics:
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
